# For a complete introduction, visit the official docs at: https://espanso.org/docs/
matches:
# current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"